services:
    db:
          image: postgres:16
          restart: always
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: autograder
          volumes:
            - pg_data:/var/lib/postgresql/data
          ports:
            - "5432:5432"
          networks:
            - db_network
    web:
        build:
          context: .
          dockerfile: Dockerfile
        entrypoint:
          [
            "/bin/sh",
            "-c",
            "git config --global --add safe.directory /home/tjctgrader/autograder && \
            /bin/sh entrypoint.sh"
          ]
        ports:
            - "3000:3000"
        networks:
            - db_network
        volumes:
            - ./:/home/tjctgrader/autograder
        depends_on:
          - db

    

networks:
  db_network:
    driver: bridge

volumes:
  pg_data: