# Generated by Django 5.2.14 on 2026-09-13 16:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Duel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to be accepted"),
                            ("active", "In progress"),
                            ("finished", "Finished"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rating_min", models.IntegerField(default=800)),
                ("rating_max", models.IntegerField(default=1200)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated Codeforces tags.",
                        max_length=200,
                    ),
                ),
                ("cf_contest_id", models.IntegerField(blank=True, null=True)),
                ("cf_index", models.CharField(blank=True, max_length=5)),
                ("cf_name", models.CharField(blank=True, max_length=200)),
                ("cf_rating", models.IntegerField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=45)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solved", "Solved"),
                            ("forfeit", "Forfeit"),
                            ("timeout", "Ran out of time"),
                            ("voided", "Voided by staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("selection_error", models.CharField(blank=True, max_length=300)),
                (
                    "bracket_match",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unused; placeholder for the Blitz Cup bracket.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="duels.duel",
                    ),
                ),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_challenged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duels_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DuelSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cf_submission_id", models.BigIntegerField()),
                ("verdict", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField()),
                (
                    "duel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="duels.duel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("duel", "cf_submission_id"),
                        name="duelsubmission_unique_per_duel",
                    )
                ],
            },
        ),
    ]
