# Generated by Django 5.2.5 on 2025-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0012_problem_contest_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="interactor_file",
            field=models.FileField(
                blank=True, null=True, upload_to="problem_interactors/"
            ),
        ),
    ]
