# Generated by Django 5.2.5 on 2025-10-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0013_problem_interactor_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="interactor_file",
        ),
        migrations.AddField(
            model_name="problem",
            name="max_queries",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
