# Generated by Django 5.2.7 on 2025-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_problem_interactor_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='interactor_file',
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
