# Generated by Django 5.2.14 on 2026-09-13 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0003_contest_writers"),
        ("problems", "0014_remove_problem_interactor_file_alter_problem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contests.contest",
            ),
        ),
    ]
