# Generated by Django 5.2.13 on 2026-05-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_remove_problem_interactor_file_alter_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='codeforces_zip',
            field=models.FileField(blank=True, upload_to='problem_testcases/'),
        ),
    ]
