# Generated by Django 5.1.7 on 2025-10-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0010_graderuser_particles_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="graderuser",
            name="use_writer_formula",
            field=models.BooleanField(default=False),
        ),
    ]

