# Generated by Django on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0011_graderuser_use_writer_formula"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemOfTheWeek",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.CharField(choices=[("beginner", "Beginner"), ("advanced", "Advanced")], max_length=20, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
