# Generated by hand on 2025-12-19
from django.db import migrations


def create_intermediate(apps, schema_editor):
    PoTW = apps.get_model('index', 'ProblemOfTheWeek')
    PoTW.objects.get_or_create(level='intermediate', defaults={'title': '', 'link': None})


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_add_problemoftheweek'),
    ]

    operations = [
        migrations.RunPython(create_intermediate, reverse_code=migrations.RunPython.noop),
    ]
