# Generated by Django 5.2.7 on 2026-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_add_intermediate_potw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemoftheweek',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='problemoftheweek',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
