# Generated by Django 5.2.14 on 2026-09-13 01:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("problems", "0014_remove_problem_interactor_file_alter_problem_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("potw", "Problem of the Week"),
                        ],
                        default="lecture",
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Lecture date, or the week for a POTW set.",
                        null=True,
                    ),
                ),
                (
                    "label_style",
                    models.CharField(
                        choices=[
                            ("letters", "Letters (A, B, C)"),
                            ("numbers", "Numbers (1, 2, 3)"),
                            ("none", "No labels"),
                        ],
                        default="letters",
                        max_length=10,
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Unpublished sets are only visible to staff.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LectureSetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("external_title", models.CharField(blank=True, max_length=200)),
                ("external_url", models.URLField(blank=True)),
                ("cf_contest_id", models.IntegerField(blank=True, null=True)),
                ("cf_index", models.CharField(blank=True, max_length=5)),
                (
                    "lecture_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="lectures.lectureset",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ("order", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("external_url", ""), ("problem__isnull", False)),
                            models.Q(
                                ("problem__isnull", True),
                                models.Q(("external_url", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="problemsetentry_internal_xor_external",
                    )
                ],
            },
        ),
    ]
